### ISSUE TITLE
Bump credhub cli version and use package management (e.g. go dep)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/terraform-secure-backend#1]
The credhub cli version is currently vendored and I could not easily spot which version it was (as it it rebased, and not using a submodule). A package management such as [go dep](https://golang.github.io/dep/) might help. 

A bump might also help as the credhub cli needs to be in sync with the credhub server e.g. in order to use the newer api and stop using deprecated apis.

**Comment by ArthurHlt** [comment]
i'm not sure about what you means by "as it it rebased, and not using a submodule". This project use [govendor](https://github.com/kardianos/govendor) which does works like go deps, i'm not just a big fan of config file for go deps (and as it is experimental for now, i prefer use govendor).

I did not use a version directly inside govendor and that's could be a mistake. Here find the version was possible by finding revision: https://github.com/orange-cloudfoundry/terraform-secure-backend/blob/master/vendor/vendor.json#L280 and go to main repo with the revision (or use directly git: https://github.com/cloudfoundry-incubator/credhub-cli/commit/1a88d96dfb501da0a92b88b5ee647ebc03615b83 (from here we can see tag associated to commit, so version 1.7.5)

**Comment by gberche-orange** [comment]
@ArthurHlt sorry I had missed with vendor.json file. Thanks for the credhub cli bump.
